# Generated by Django 4.0.3 on 2022-03-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=60, null=True)),
                ('mes', models.TextField(null=True)),
                ('avt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chinh.images')),
            ],
        ),
    ]
