# Generated by Django 4.0.3 on 2022-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinh', '0003_usr_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usr',
            name='mk',
            field=models.TextField(null=True),
        ),
    ]
