# Generated by Django 4.0.3 on 2022-04-06 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinh', '0004_usr_data_usr_mk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(null=True)),
                ('lb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chinh.label')),
            ],
        ),
    ]
