# Generated by Django 4.0.3 on 2022-04-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinh', '0005_label_cau'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='res',
            field=models.TextField(null=True),
        ),
    ]
