# Generated by Django 4.0.3 on 2022-04-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinh', '0008_label_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='ip',
            field=models.TextField(null=True),
        ),
    ]
