# Generated by Django 4.0.3 on 2022-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinh', '0009_alter_usr_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='nm',
            field=models.TextField(null=True),
        ),
    ]
